services:
  web:
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: docker.dev/caffe_notebook:gpu
    ports:
    - '8888'
    restart: always
    volumes:
    - /mfs/replicated/datasets/caffe_models:/data
    - /mfs/replicated/dockers/resnet50-caffe/data/test_images:/images
    - /mfs/replicated/notebooks:/workspace
    - nvidia_driver_367.48:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.48:
    external: true
