services:
  web:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    ports:
    - '8888'
    volumes:
    - .:/notebooks/
    - /mfs/replicated/datasets/inception:/data/
    - nvidia_driver_367.48:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.48:
    external: true
