services:
  caffe_finetuning:
    command: bash
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: caffe:gpu
    volumes:
    - $PWD:/workspace/
    - /home/eva/git/image-analyzer-data/:/data/images
    - /mfs/replicated/datasets/caffe_models/:/data/models
    - nvidia_driver_367.48:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.48:
    external: true
